/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
}

group = "com.kolhey.p2p"
version = "1.0-SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val osName = System.getProperty("os.name").lowercase()
val osArch = System.getProperty("os.arch").lowercase()

val quicNativeClassifier = when {
    osName.contains("mac") && (osArch.contains("aarch64") || osArch.contains("arm64")) -> "osx-aarch_64"
    osName.contains("mac") -> "osx-x86_64"
    osName.contains("linux") && (osArch.contains("aarch64") || osArch.contains("arm64")) -> "linux-aarch_64"
    osName.contains("linux") -> "linux-x86_64"
    osName.contains("win") -> "windows-x86_64"
    else -> throw GradleException("Unsupported OS/arch for Netty QUIC native library: $osName / $osArch")
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)

    // JavaFX for GUI
    val javafxVersion = "21.0.3"
    val javafxPlatform = when {
        osName.contains("win") -> "win"
        osName.contains("mac") && osArch.contains("aarch64") -> "mac-aarch64"
        osName.contains("mac") -> "mac"
        osName.contains("linux") -> "linux"
        else -> throw GradleException("Unsupported OS for JavaFX: $osName / $osArch")
    }
    
    implementation("org.openjfx:javafx-controls:$javafxVersion:$javafxPlatform")
    implementation("org.openjfx:javafx-fxml:$javafxVersion:$javafxPlatform")
    implementation("org.openjfx:javafx-graphics:$javafxVersion:$javafxPlatform")
    implementation("org.openjfx:javafx-swing:$javafxVersion:$javafxPlatform")

    implementation("io.netty:netty-all:4.1.107.Final")
    implementation("io.netty.incubator:netty-incubator-codec-classes-quic:0.0.62.Final")
    runtimeOnly("io.netty.incubator:netty-incubator-codec-native-quic:0.0.62.Final:$quicNativeClassifier")
    implementation("org.bouncycastle:bcprov-jdk18on:1.78.1")
    implementation("org.bouncycastle:bcpkix-jdk18on:1.78.1")

    implementation("org.jmdns:jmdns:3.5.9")

    implementation("org.xerial:sqlite-jdbc:3.45.1.0")

    testImplementation("org.junit.jupiter:junit-jupiter-api:6.0.1")

    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:6.0.1")
    testRuntimeOnly("io.netty.incubator:netty-incubator-codec-native-quic:0.0.62.Final:$quicNativeClassifier")

    testImplementation("org.mockito:mockito-core:5.11.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.11.0")

}

tasks.test {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    systemProperty("p2p.allowInsecureDevTls", "true")

    testLogging {
        events("passed", "skipped", "failed")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showExceptions = true
        showCauses = true
        showStackTraces = true
    }
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("6.0.1")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.kolhey.p2p.Main"
}

<<<<<<< HEAD
tasks.run.get().apply {
    // Pass system properties to the run task for development mode
    systemProperties["p2p.allowInsecureDevTls"] = System.getProperty("p2p.allowInsecureDevTls") ?: "true"
=======
// GUI task
tasks.register("runGui", JavaExec::class) {
    group = "application"
    description = "Run the P2P File Sharing GUI application"
    mainClass = "com.kolhey.p2p.gui.P2PFileShareApp"
    classpath = sourceSets["main"].runtimeClasspath
    jvmArgs = listOf(
        "--add-modules", "javafx.controls,javafx.fxml",
        "--add-opens", "javafx.graphics/com.sun.javafx.scene.behavior=ALL-UNNAMED"
    )
>>>>>>> fbbd9eb (gui)
}
