package com.kolhey.p2p.security;

import javax.net.ssl.X509TrustManager;

import com.kolhey.p2p.repository.PeerRepository;

import java.security.MessageDigest;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;
import java.util.HexFormat;

/**
 * PeerIdentityTrustManager implements Trust-On-First-Use (TOFU) verification.
 * 
 * TOFU Workflow:
 * 1. First connection from unknwon peer: Extract fingerprint, auto-trust & store it
 * 2. Subsequent connections: Verify fingerprint matches stored value
 * 3. Fingerprint mismatch: Reject connection (potential MITM attack)
 * 4. Revocation: Admin can revoke peer trust via peerDatabase.revokePeer()
 * 
 * This ensures:
 * - Zero-config peer discovery (no pre-registration needed)
 * - Protection against certificate substitution attacks
 * - Clear audit trail of when each peer was first trusted
 */
public class PeerIdentityTrustManager implements X509TrustManager {

    private final PeerRepository peerDatabase;
    private final boolean enableTofu; // Trust-On-First-Use mode

    /**
     * @param peerDatabase database storing trusted peer fingerprints
     * @param enableTofu   if true, auto-trust unknown peers on first connection
     *                     if false, reject unknown peers (requires pre-registration)
     */
    public PeerIdentityTrustManager(PeerRepository peerDatabase, boolean enableTofu) {
        this.peerDatabase = peerDatabase;
        this.enableTofu = enableTofu;
    }

    /**
     * Backward-compatible constructor - defaults to TOFU enabled
     */
    public PeerIdentityTrustManager(PeerRepository peerDatabase) {
        this(peerDatabase, true); // TOFU enabled by default for zero-config networking
    }

    @Override
    public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {
        verifyPeerIdentity(chain[0], "client");
    }

    @Override
    public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {
        verifyPeerIdentity(chain[0], "server");
    }

    @Override
    public X509Certificate[] getAcceptedIssuers() {
        return new X509Certificate[0]; 
    }

    /**
     * TOFU Verification Logic
     */
    private void verifyPeerIdentity(X509Certificate cert, String role) throws CertificateException {
        try {
            byte[] publicKey = cert.getPublicKey().getEncoded();
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(publicKey);
            String fingerprint = HexFormat.of().formatHex(hash);
            String shortFp = fingerprint.substring(0, 8) + "...";

            // Check if peer already registered
            if (peerDatabase.isTrusted(fingerprint)) {
                System.out.println("[Security] " + role + " peer verified by fingerprint: " + shortFp);
                return;
            }

            // Unknown peer - apply TOFU logic
            if (enableTofu) {
                // TOFU MODE: Auto-trust on first use
                String autoGeneratedName = "Peer-" + shortFp;
                peerDatabase.trustPeer(autoGeneratedName, fingerprint);
                
                System.out.println("\n[TOFU - First Use] New peer auto-trusted!");
                System.out.println("  -> Fingerprint: " + fingerprint);
                System.out.println("  -> Assigned Name: " + autoGeneratedName);
                System.out.println("  -> Stored in database. Future connections from this peer will verify against this fingerprint.\n");
                return;
            } else {
                // STRICT MODE: Reject unknown peers
                System.err.println("\n[SECURITY] Unknown peer rejected!");
                System.err.println("  -> Fingerprint: " + fingerprint);
                System.err.println("  -> Action: Connection dropped (TOFU disabled, pre-registration required)\n");
                
                throw new CertificateException("Unknown peer. Pre-registration required or enable TOFU mode.");
            }

        } catch (CertificateException e) {
            throw e; // Re-throw CertificateException as-is
        } catch (Exception e) {
            throw new CertificateException("Cryptographic failure during verification", e);
        }
    }
}